### ISSUE TITLE
Update rust programs to 1.0 alpha when it comes out in a couple of weeks

### ISSUE THREAD

**Issue by alexschneider** [rtoal/polyglot#16]
According to [Mozilla](http://blog.rust-lang.org/2014/12/12/1.0-Timeline.html), Rust should hit the 1.0 milestone on Friday, Jan 9, 2015 for the alpha. This should certainly be updated for that.

**Comment by rtoal** [comment]
Okay, Alex, ping! I updated triple and anagrams to the best of my ability. Triple looks good, but anagrams looks like a mess. I just guessed and cast stuff until it worked! Can you take a look please? Thanks.
