### ISSUE TITLE
Go Animals

### ISSUE THREAD

**Issue by rtoal** [rtoal/polyglot#20]
We all know Go doesn't have classic OO with abstract methods and subclasses and all that.  Ruby and Python do, so check out the `animals` scripts in those folders, and build the same thing in Go.  Reassign to jadengore if you are busy.

**Comment by rtoal** [comment]
I've done an implementation but it looks weird.

**Comment by rtoal** [comment]
Reassigning to Ed. I think Zane is enjoying the holidays.

**Comment by jadengore** [comment]
I think you already implemented this, maybe this issue can be closed?

**Comment by rtoal** [comment]
Yes, I had forgotten about it.

On Jan 21, 2015, at 6:47 PM, Edward Bramanti <notifications@github.com<mailto:notifications@github.com>> wrote:


I think you already implemented this, maybe this issue can be closed?
