### ISSUE TITLE
Vector class in Swift

### ISSUE THREAD

**Issue by rtoal** [rtoal/polyglot#40]
There is a small vector implementation in Lua, Python, and Erlang. An equivalent is needed in modern, perfect, elegant, Swift.

**Comment by mwflickner** [comment]
There are a few ways to do this. Do you want Ints or Doubles? And for the toString equivalent, do you want it to match the Python, Erlang, and Lua? It is most elegant if I don't but doesn't add much more if I do.

**Comment by mwflickner** [comment]
I can also add other functions that use prefix and postfix operators like negation with -, compound assignment operators like ++ or +=, equivalence operators with == and != if you want.

As of right now I'll send a branch shortly with just the basic stuff that matches the other ones exactly.

**Comment by jadengore** [comment]
@mwflickner Keep in mind that pre and post increment operators will be removed from Swift: https://github.com/apple/swift-evolution/blob/master/proposals/0004-remove-pre-post-inc-decrement.md

**Comment by rtoal** [comment]
Keep it just as minimal as the existing Erlang and Python and Lua examples.

**Comment by mwflickner** [comment]
@jadengore not surprised honestly.
@rtoal Just threw up a PR

**Comment by jadengore** [comment]
@rtoal Done!
